// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  var printer;
  Crafty.e('2D, DOM, Text').text('Click to restart the timer').attr({
    x: 200,
    y: 100,
    w: 200
  });
  printer = Crafty.e("TimePrinter");
  printer.expiresIn(10, true);
  return Crafty.addEvent(this, Crafty.stage.elem, "mousedown", function(e) {
    console.log('mouse down');
    return printer.addSeconds(5, true);
  });
});
