// Generated by CoffeeScript 1.7.1
Crafty.scene('Game', function() {
  var iso, obj;
  iso = Crafty.isometric.size(128);
  obj = Crafty.e("ShiftingSprite").shiftingSprite('grass', 'stone');
  iso.place(1, 1, 0, obj);
  return Crafty.addEvent({}, window.document, "click", function(event) {
    var pos;
    pos = iso.px2pos(event.clientX, event.clientY);
    console.log('DOM mouse down event', event, pos);
    return iso.place(pos.x, pos.y, 0, Crafty.e("ShiftingSprite").shiftingSprite('grass', 'stone'));
  });
});
