// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  var iso;
  iso = Crafty.diamondIso.init(128, 128, 20, 20);
  return Crafty.addEvent({}, Crafty.stage.elem, "mousedown", function(event) {
    console.log('Mouse down', event);
    return iso.place(2, 1, 0, Crafty.e('2D, DOM, Color').color('red').attr({
      w: 128,
      h: 128
    }));
  });
});
