// Generated by CoffeeScript 1.7.1
Crafty.c('CenterText', {
  init: function() {
    this.requires('2D, DOM, Text');
    return this.recenter();
  },
  recenter: function() {
    this.attr({
      x: (Crafty.viewport.width - this.attr('w')) / 2,
      y: (Crafty.viewport.height - this.attr('h')) / 2
    });
    return this;
  }
});
