// Generated by CoffeeScript 1.7.1
Crafty.c('CenterText', {
  init: function() {
    this.requires('2D, DOM, Text');
    return this.attr({
      x: Crafty.DOM.window.width / 2,
      y: Crafty.DOM.window.height / 2
    });
  }
});
