// Generated by CoffeeScript 1.7.1
Crafty.c('Circle', {
  init: function() {
    console.log('Circle init');
    this.requires('2D, DOM, Text');
    this.text('Mouse click');
    return this;
  },
  at: function(x, y) {
    this.attr({
      x: x,
      y: y
    });
    return this;
  }
});
