// Generated by CoffeeScript 1.7.1
Crafty.c('Grid', {
  Grid: function(width, height) {
    this.attr('gridW', width);
    this.attr('gridH', height);
    return this;
  },
  place: function(x, y) {
    var values;
    values = this._setGrid();
    console.log('Place', values);
    console.log(x, y);
    this.attr({
      x: x * values.w,
      y: y * values.h
    });
    console.log(this);
    return this;
  },
  _setGrid: function() {
    var h, w;
    w = this.attr('gridW');
    if (!w) {
      this.attr('gridW', this.h);
    }
    h = this.attr('gridH');
    if (!h) {
      this.attr('gridH', this.h);
    }
    return {
      h: this.attr('gridH'),
      w: this.attr('gridW')
    };
  }
});
