// Generated by CoffeeScript 1.7.1
Crafty.c('HighlightedSprite', {
  init: function() {
    var selector;
    this.requires("2D, DOM, Mouse");
    this.areaMap([64, 0], [128, 32], [128, 96], [64, 128], [0, 96], [0, 32]);
    this.bind('Click', this.onClick);
    selector = Crafty.e('2D, DOM, highlighter').attr({
      x: -1000,
      y: -1000
    });
    return this.attr('selector', selector);
  },
  toggleSelect: function(selected) {
    if (selected == null) {
      selected = null;
    }
    if (!selected) {
      selected = this.attr('selected');
    }
    if (selected) {
      return this.unselect();
    } else {
      return this.select();
    }
  },
  select: function() {
    var sel;
    this.attr('selected', true);
    sel = this.attr('selector');
    return sel.attr({
      x: this.x,
      y: this.y,
      z: this.z - 1
    });
  },
  unselect: function() {
    var sel;
    this.attr('selected', false);
    sel = this.attr('selector');
    return sel.attr({
      x: -1000,
      y: -1000
    });
  },
  onClick: function(event) {
    console.log('Click', event, this);
    event.stopPropagation();
    return this.toggleSelect();
  }
});
