// Generated by CoffeeScript 1.7.1
Crafty.c('SelectedSprite', {
  init: function() {
    this.requires("2D, DOM, Mouse");
    this.areaMap([64, 0], [128, 32], [128, 96], [64, 128], [0, 96], [0, 32]);
    return this.bind('Click', this.onClick);
  },
  selectedSprite: function(first, second) {
    this.attr({
      normSprite: first,
      selSprite: second,
      selected: false
    });
    this.addComponent(first);
    return this;
  },
  toggleSprite: function() {
    console.log('Toggle');
    if (this.attr('selected')) {
      this.attr('selected', false);
    } else {
      this.attr('selected', true);
    }
    this.toggleComponent(this.attr('normSprite'), this.attr('selSprite'));
    return this;
  },
  onClick: function(event) {
    console.log('Click', event, this);
    event.stopPropagation();
    return this.toggleSprite();
  }
});
