// Generated by CoffeeScript 1.7.1
Crafty.c('ShiftingSprite', {
  init: function() {
    this.requires("2D, DOM, Mouse");
    this.areaMap([64, 0], [128, 32], [128, 96], [64, 128], [0, 96], [0, 32]);
    this.bind('Click', this.onClick);
    this.bind('MouseOver', this.onMouseOver);
    return this.bind('MouseOut', this.onMouseOut);
  },
  shiftingSprite: function(first, second) {
    this.attr({
      sprites: [first, second],
      selected: 0
    });
    return this.addComponent(first);
  },
  toggleSprite: function() {
    var newSelected, selected, sprites;
    sprites = this.attr('sprites');
    selected = this.attr('selected');
    newSelected = selected + 1;
    if (newSelected > 1) {
      newSelected = 0;
    }
    console.log(sprites);
    console.log(selected);
    console.log(newSelected);
    this.removeComponent(sprites[selected]);
    this.addComponent(sprites[newSelected]);
    return this.attr('selected', newSelected);
  },
  onClick: function(event) {
    console.log(event);
    event.stopPropagation();
    return this.toggleSprite();
  },
  onMouseOver: function() {
    return console.log('onMouseOver', this);
  },
  onMouseOut: function() {
    return console.log('onMouseOut', this);
  }
});
