// Generated by CoffeeScript 1.7.1
Crafty.c('TimePrinter', {
  init: function() {
    var self;
    this.requires('2D, DOM, Text, Timer');
    this.attr({
      x: 100,
      y: 100,
      w: 200
    });
    self = this;
    return this.bind('RenderScene', function() {
      return self.render();
    });
  },
  render: function() {
    return this.text('' + this._secondsLeft + ' seconds');
  }
});
