// Generated by CoffeeScript 1.7.1
Crafty.c('Timer', {
  _stopFunc: null,
  _expireTime: null,
  _secondsLeft: null,
  start: function() {
    var self;
    if (this._stopFunc) {
      return;
    }
    if (this._calculateTime <= 0) {
      return;
    }
    self = this;
    this._stopFunc = Crafty.bind('EnterFrame', function() {
      return self._calculateTime();
    });
    return this;
  },
  stop: function() {
    if (!this._stopFunc) {
      return;
    }
    Crafty.unbind('EnterFrame', this._stopFunc);
    this._stopFunc = null;
    return this;
  },
  expiresIn: function(seconds, autoStart) {
    if (autoStart == null) {
      autoStart = false;
    }
    this._expireTime = Date.now() + (seconds * 1000);
    if (autoStart) {
      this.start();
    }
    return this;
  },
  addSeconds: function(seconds, autoStart) {
    if (autoStart == null) {
      autoStart = false;
    }
    if (this._secondsLeft <= 0) {
      this._expireTime = Date.now();
    }
    this._expireTime += seconds * 1000;
    if (autoStart) {
      this.start();
    }
    return this;
  },
  _calculateTime: function(event) {
    var left, now;
    now = Date.now();
    left = this._expireTime - now;
    this._secondsLeft = Math.floor(left / 1000);
    if (this._secondsLeft <= 0) {
      this.stop();
    }
    return this._secondsLeft;
  }
});
