// Generated by CoffeeScript 1.7.1
Crafty.scene('main', function() {
  var height, width, x, y, _i, _results;
  width = Crafty.viewport.width / 128;
  height = Crafty.viewport.height / 128;
  console.log(width);
  console.log(height);
  _results = [];
  for (x = _i = 0; 0 <= width ? _i < width : _i > width; x = 0 <= width ? ++_i : --_i) {
    _results.push((function() {
      var _j, _results1;
      _results1 = [];
      for (y = _j = 0; 0 <= height ? _j < height : _j > height; y = 0 <= height ? ++_j : --_j) {
        _results1.push(Crafty.e("SelectedSprite, Grid").selectedSprite('grass', 'grassSel').place(x, y));
      }
      return _results1;
    })());
  }
  return _results;
});
