// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  return Crafty.addEvent({}, Crafty.stage.elem, "mousedown", function(event) {
    return Crafty.e("Circle").at(event.x, event.y);
  });
});
