// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  var colorText, colors, currColor;
  colors = ['#ff0000', '#00FF00', '#0000FF'];
  currColor = 0;
  colorText = Crafty.e('2D, DOM, Text').textColor(colors[currColor]).attr({
    x: 50,
    y: 50,
    w: 200
  }).text('Current Color');
  return Crafty.addEvent({}, Crafty.stage.elem, "mousedown", function(event) {
    if (event.button === 2) {
      currColor += 1;
      if (currColor >= colors.length) {
        currColor = 0;
      }
      return Crafty('Text').each(function() {
        console.log(this);
        return this.textColor(colors[currColor]);
      });
    } else {
      return Crafty.e("Circle").Circle(40, colors[currColor]).attr({
        x: event.x,
        y: event.y
      });
    }
  });
});
